import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./Provider";
import { Toaster } from "react-hot-toast";
import Loader from "./loading";
import { useLoadUserQuery } from "@/redux/features/api/apiSlice";
import { FC } from "react";
import CustomSessionProvider from "./SessionProvider/CustomSessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <CustomSessionProvider>
            {children}
            <Toaster position="top-center" reverseOrder={false} />
          </CustomSessionProvider>
        </Providers>
      </body>
    </html>
  );
}

const Custom: FC<{children: React.ReactNode}> = ({children}) =>{
  const {isLoading} = useLoadUserQuery({});

  return (
    <>
    {
      isLoading ? <Loader /> : <>{children}</>
    }
    </>
  )
}